### PR TITLE
Update for changes on 2024-02-22

### PR DESCRIPTION
**Pull request by yut23**
Fixes: #28

### CODE REVIEW

**Comment by fadster** [comment]
Thank you so much!

**Comment by fadster** [comment]
I'm not sure if this was the case before this fix, but the three dots button that opens the "About this result" sidebar is missing. Would it be possible to display it somewhere, perhaps to the right of the URL?

**Comment by uahim** [comment]
@fadster I do see the dots with this very fix in both Violentmonkey and Greasemonkey in different browsers actually

**Review by drwonky — APPROVED** [review]

**Comment by fadster** [comment]
@uahim The problem must be on my end then. Could you please tell me what browsers you tested it on?

**Comment by yut23** [comment]
> @uahim The problem must be on my end then. Could you please tell me what browsers you tested it on?

It works as expected with Tampermonkey 5.0.1 on Chrome 118.0.5993.70 and Firefox 116.0. I've noticed it occasionally gets wrapped to the next line; I'm not sure why. I've also seen it break once or twice with a slow network connection.

**Comment by uahim** [comment]
> @uahim The problem must be on my end then. Could you please tell me what browsers you tested it on?

try deleting cookies for the google domain and/or deleting + fresh installing the script maybe?
this has worked for me with similar glitches in the past in various browsers

and for what it's worth, the dots do appear, but do nothing in palemoon (but that's google being google: evil and sending different markup to different browsers I guess)

**Pull request merged**
