### PR TITLE
Update for changes on 2023-09-08

### PR DESCRIPTION
**Pull request by yut23**
Fixes: #24

### CODE REVIEW

**Comment by virtualdj** [comment]
Thanks, it works for me!

**Comment by strongBurger** [comment]
this seem to fix the problem, thank you

**Review by drwonky — APPROVED** [review]

**Comment by drwonky** [comment]
Tested, works as expected, thanks!

**Comment by gaveitatry2** [comment]
@yut23 - Thanks for fixing it. I have no idea why Google keeps making Google Search worse with every update. It was bad enough the first time they changed the layout, but this last update was even way worse than that!

**Pull request merged**
