### PR TITLE
Include new google homepage changes

### PR DESCRIPTION
**Pull request by tejaslodaya**

### CODE REVIEW

**Comment by tejaslodaya** [comment]
Solves #2 and #3

**Comment by GTANAdam** [comment]
Yeap, that does it.

**Comment by aligo** [comment]
Yeah, sorry for the late reply and thanks. @tejaslodaya @GTANAdam

**Comment by Perty65** [comment]
Thanks a ton. You saved my life. I am highly grateful to you.

I can't stand the current UGLY looks of Google. 

You made my Life. Cheers!

**Pull request merged**
